### model
model_name_or_path: /home/leon/Model/ModelScope/models/Qwen/Qwen2.5-7B-Instruct
quantization_bit: 4
quantization_method: bnb
double_quantization: true
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target: all

### dataset
dataset: compliance_qa
dataset_dir: /home/leon/GitHub/Paper/2022_LoRA/practice_qlora/dataset
template: qwen
cutoff_len: 1024
preprocessing_num_workers: 4

### output
output_dir: /home/leon/Output/2022_LoRA/qwen25-7b/qlora/compliance_qa
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: epoch
